version: '3.8'

services:
  laravel_php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: laravel_php
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
      - ./storage:/var/www/html/storage
      - ./custom-php.ini:/usr/local/etc/php/conf.d/custom-php.ini
    networks:
      - laravel
    depends_on:
      - laravel_db

  laravel_web:
    image: nginx:alpine
    container_name: laravel_web
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel
    depends_on:
      - laravel_php

  laravel_db:
    image: mysql:8.0
    container_name: laravel_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: sistema_gestao
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel

  laravel_admin:
    image: phpmyadmin/phpmyadmin
    container_name: laravel_admin
    restart: unless-stopped
    environment:
      PMA_HOST: laravel_db
      PMA_USER: root
      PMA_PASSWORD: 123456
    ports:
      - "8081:80"
    networks:
      - laravel

networks:
  laravel:

volumes:
  mysql_data:
